name: Conan development
on:
  push:
    tags:
      - '*'
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v2
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      - name: Create default profile
        run: conan profile new default --detect
      - name: Update profile 11
        run: conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Update profile version
        run: conan profile update settings.compiler.version=10 default
      - name: setup conan
        run: |
          conan config set general.revisions_enabled=True 
          conan remote add proofofwork https://conan.pow.co/artifactory/api/conan/conan
          conan user -p ${{ secrets.CONAN_USER_KEY }} -r proofofwork github
          export CURRENT_VERSION=$RELEASE_VERSION
          conan install . -r proofofwork
          conan create . proofofwork/unstable -r proofofwork
          conan upload test/${CURRENT_VERSION}@proofofwork/unstable -r proofofwork --all
      - name: prepare release package
        run: |
          mkdir build && cd build
          conan install .. -r=proofofwork
          cmake .. -DPACKAGE_TESTS=Off
          cmake --build .
          cp ../include ./
          tar -czvf test-${$RELEASE_VERSION}.tar.gz include lib
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: build/test-${$RELEASE_VERSION}.tar.gz
          name: test-${$RELEASE_VERSION}.tar.gz
